### PR TITLE
increasing picard memory

### PR DESCRIPTION
**Pull request by IanSudbery**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Is this something that should be parametrized instead in pipeline.ini?

**Comment by IanSudbery** [comment]
In thoery Picard tools are desinged to use no more than 2G. They are java progs and our launch scripts are configured to specify 2G of memory as well.

**Comment by AndreasHeger** [comment]
getPicardOptions uses -l mem_free - should this not be changed to mem_free?

**Comment by IanSudbery** [comment]
probably. Its just convenient as it is at the moment because its in one place rather than in each of the functions that call getPicardOptions. I'll get round to altering it at some point.

**Pull request merged**
