### PR TITLE
Ac shortstack

### PR DESCRIPTION
**Pull request by Acribbs**
Added shortstack mapper for short RNA read mapping

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Many thanks @Acribbs !

Could anybody else have a look at it before merging please?

**Comment by MikeDMorgan** [comment]
The mapper class is referred to as `Shortread`, yet the instantiation refers to `Shortstack`, ergo it will fail.

**Comment by Acribbs** [comment]
Sorry, I’m not seeing it, I have the mapper class referring to shortstack?

**Comment by MikeDMorgan** [comment]
My bad, GitHub was only showing a subset of the commits, not all of the changes in PipelineMapping.py.  Apologies, it looks fine.

**Comment by sebastian-luna-valero** [comment]
Many thanks!

**Pull request merged**
