### PR TITLE
Sns fix memory pipeline genesets

### PR DESCRIPTION
**Pull request by snsansom**
The pipeline was crashing on our cluster because jobs were exceeding the amount of memory that they had requested.

To fix, the amount of memory for all cluster jobs is now specificed in the pipeline.ini  - by default 4G for standard tasks and 20G for "highmemory" tasks (inspection with top showed one task to be using 15G!).

Pipeline now completes successfully for ensembl version 91 for both mouse and human annotations.

### CODE REVIEW

**Comment by Acribbs** [comment]
Brilliant! Its things like this we would miss when testing on the cgat cluster. Wow, 15G sounds like a lot, which task was it?, I think kevin mentioned it in an email but I have lost it.

**Comment by Acribbs** [comment]
sorry scratch that last comment, I looked through the code and easily spotted it.

**Comment by sebastian-luna-valero** [comment]
Jenkins is happy in the CGAT cluster as well, so merging.

Many thanks @snsansom

**Comment by AndreasHeger** [comment]
Note for porting to CGATCore: Probably not necessary as should be possible generically using two mechanisms:
1. using **kwargs in function definition
2. using the PARAMS dictionary.

**Pull request merged**
