### PR TITLE
buildGeneprofile running with non-spliced mapper added active_if stat…

### PR DESCRIPTION
**Pull request by Acribbs**
…ement

### CODE REVIEW

**Comment by jscaber** [comment]
Hi @Acribbs 
I added this feature recently and it is not just useful for spliced mapping.
For example it is extremely useful for CHIP and CLIP, to see where your reads are falling within genes.
Just a suggestion, but I would keep it in as default.

**Comment by Acribbs** [comment]
Hi @jscaber 
Problem is at the moment the pipeline fails if you do not have spliced mapping because a it depends on having a gif created by def buildCodingExons, however this is not ran unless spliced mapping function is specified. Any suggestions on a work around?

**Comment by jscaber** [comment]
Ahh, sorry - I did run the with a non-spliced mapper but it kept failing at the mapping stage so must have missed this error - apologies.
Options would be
1. remove active_if from buildCodingExons - I don't think that takes particularly long
2. add another entry in pipeline.ini which allows to run this even for non spliced aligners
Either fine with me, happy to help with implementation.

**Comment by Acribbs** [comment]
After discussions with @Charlie-George we have decided to go with the first option. She has tested it but please have a look and see if iv implemented correctly.

Thanks

**Comment by jscaber** [comment]
Thanks, looks fine, and sorry for my sloppy work in the first place!

**Comment by Acribbs** [comment]
You can be excused for being not perfect all the time :)

**Comment by sebastian-luna-valero** [comment]
Thanks!

**Pull request merged**
