### PR TITLE
Ac input validation

### PR DESCRIPTION
**Pull request by Acribbs**
There is a new option to perform input validation on the pipeline.ini. When running a pipeline if you add the command line option `--input-validation` a series of warnings will be produced if options are missing or a file path or directory is missing or not accessible. Before running the pipeline you will have to then decide whether you are happy before typing Y to continue or n to stop. @CGATOxford/contributors I have tested it on the pipelines I am currently working on but maybe worth testing on other pipelines too.

### CODE REVIEW

**Comment by Charlie-George** [comment]
Test to see if adam gets the reply

**Comment by sebastian-luna-valero** [comment]
Thanks both!

It would be great if you guys could run it with your pipelines and see whether the extra help provided is useful or not (and add your own ideas to it!)

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Hi everyone,

Following up on this first version of input validation for pipelines, can I ask the following question: if we want to check whether a file is readable in the `pipeline.ini`, would it make sense just to expect and absolute path to the input file? if not, what other pattern would you suggest?

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
So far the input validation is optional and quite basic but will merge into the master until I can focus on this further.

**Pull request merged**
