### PR TITLE
Refactor Pipeline module DRMAA abstraction into Cluster.py sub-module.

### PR DESCRIPTION
**Pull request by snsansom**
Further refactoring to make the code base queue-manager agnostic.
- Refactoring is needed to allow a common DRMAA abstraction for both the Pipeline module and farm.py. The abstracted functions are in the Pipeline/Cluster.py module so that they can be imported into farm.py. If preferred they could go into Pipeline/Utils.py or elsewhere.
- farm.py cluster parameters still come from CGAT/Experiment.py to which extra cluster parameters (inc cluster_queue_manager) have been added (see corresponding pull request). The cmd-farm parameter is correspondingly updated in Pipeline/Parameters.py.
- A new --job-memory option is added to farm.py for setting the required memory in the absence of --cluster-memory-default (which is now the default for cmd-farm jobs). Note that setupDrmaaJobTemplate() in Pipeline/Cluster.py requires job_memory to be set. Currently the default of --job-memory in farm.py is "None" which means that in the absence of --cluster-memory-default farm.py DRMAA jobs will fail to run. I suggest that somebody recommends a sensible default. (I think it is a good idea for all DRMAA jobs to specify their memory requirements...).

### CODE REVIEW

**Comment by snsansom** [comment]
I would be happy for Andreas to consider the suggested changes to farm.py particularly regarding enforcing specification of memory requirements for DRMAA jobs.

**Comment by AndreasHeger** [comment]
Thanks, looks good. A new module Cluster.py makes sense to group all this functionality.

**Comment by MikeDMorgan** [comment]
There may be a slight side-effect of some of the cluster queue management changes.  Currently some jobs are being scheduled on to alternative queues, even when `jobs_queue = "all.q"`.  It seems the offending section in Cluster.py is from line 87 which checks for the presence of `cluster_pe_queue` only, this means that if it is not set elsewhere then jobs are only allocated according to the default scheduling and available slots for SGE.  It's generally on a few jobs that are pushed onto other queues, but they are not being reinstated properly even when resources become available again.

Can I suggest adding in a little more flow control to allow the use of `jobs_queue`?

**Comment by AndreasHeger** [comment]
Hi @MikeDMorgan, thanks, this seems to be an indentation error. Fixed by 811be73

Best wishes,
Andreas

**Pull request merged**
