### PR TITLE
added checkpoints as per issue #229 and added others that I could see…

### PR DESCRIPTION
**Pull request by Acribbs**
… needed it

### CODE REVIEW

**Comment by Acribbs** [comment]
@AndreasHeger @sebastian-luna-valero since jenkins only runs tests on the master branch, would you be able to review the checkpoints before the branch is merged. Thanks

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs 

Please see https://github.com/CGATOxford/CGATPipelines/pull/280#issuecomment-277614681

In order to run regression tests on-demand and please check whether they pass on this branch.

**Comment by sebastian-luna-valero** [comment]
@Acribbs 

I have been running `pipeline_testing.py` on this branch I have got the following issues.

Files with different checksum compared to reference:
-  test_readqc.dir/status_summary.tsv.gz
-  test_readqc.dir/basic_statistics_summary.tsv.gz
-  test_readqc.dir/export/fastqc/trimmed-SRR078586-X-R1.fastq.1_fastqc/summary.txt

Files with different number of lines compared to reference:
- test_readqc.dir/export/fastqc/trimmed-SRR089590-X-R1.fastq.1_fastqc/fastqc_data.txt
- test_readqc.dir/export/fastqc/trimmed-SRR089590-X-R1.fastq.2_fastqc/fastqc_data.txt
- test_readqc.dir/export/fastqc/trimmed-SRR078586-X-R1.fastq.1_fastqc/fastqc_data.txt
- test_readqc.dir/export/fastqc/trimmed-SRR078586-X-R1.fastq.2_fastqc/fastqc_data.txt

Which points to:
- pipeline: `readqc`
- task: `runFastqc`
- module: `PipelineMapping`
- class: `PipelineMapping.FastQc`


Would you be able to tell why?

**Comment by Acribbs** [comment]
I'm back tomorrow so can have a look at this in the morning. Briefly Glancing at the issue i can't see why this is happening, all I added was a few checkpoints (plus a spelling mistakes, oops).


On 15 Feb 2017, at 17:00, Sebastian Luna-Valero <notifications@github.com<mailto:notifications@github.com>> wrote:


@Acribbs<https://github.com/Acribbs>

I have been running pipeline_testing.py on this branch I have got the following issues.

Files with different checksum compared to reference:

  *   test_readqc.dir/status_summary.tsv.gz
  *   test_readqc.dir/basic_statistics_summary.tsv.gz
  *   test_readqc.dir/export/fastqc/trimmed-SRR078586-X-R1.fastq.1_fastqc/summary.txt

Files with different number of lines compared to reference:

  *   test_readqc.dir/export/fastqc/trimmed-SRR089590-X-R1.fastq.1_fastqc/fastqc_data.txt
  *   test_readqc.dir/export/fastqc/trimmed-SRR089590-X-R1.fastq.2_fastqc/fastqc_data.txt
  *   test_readqc.dir/export/fastqc/trimmed-SRR078586-X-R1.fastq.1_fastqc/fastqc_data.txt
  *   test_readqc.dir/export/fastqc/trimmed-SRR078586-X-R1.fastq.2_fastqc/fastqc_data.txt

Which points to:

  *   pipeline: readqc
  *   task: runFastqc
  *   module: PipelineMapping
  *   class: PipelineMapping.FastQc

Would you be able to tell why?

**Comment by sebastian-luna-valero** [comment]
Not sure whether this is related.

On this branch:
```
$ python CGATPipelines/CGATPipelines/pipeline_readqc.py printconfig | grep -i trim
('cutadapt_reroute_untrimmed', '=', 0)
('fastx_trimmer_options', '=', '-f17')
('trimgalore_options', '=', '-q 20 --length 40 --rrbs -a AGATCGGAAGAGC')
('trimmomatic_adapter', '=', '/ifs/apps/bio/trimmomatic-0.32/adapters/TruSeq2-PE.fa')
('trimmomatic_c_thresh', '=', 10)
('trimmomatic_keep_both_reads', '=', 1)
('trimmomatic_min_adapter_len', '=', 1)
('trimmomatic_mismatches', '=', 1)
('trimmomatic_options', '=', 'LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36')
('trimmomatic_p_thresh', '=', 30)
```

On `master`:
```
$ python CGATPipelines/CGATPipelines/pipeline_readqc.py printconfig | grep -i trim
('cutadapt_reroute_untrimmed', '=', 0)
('fastx_trimmer_options', '=', '-f17')
('trimgalore_options', '=', '-q 20 --length 40 --rrbs -a AGATCGGAAGAGC')
('trimmomatic_adapter', '=', '/ifs/apps/bio/trimmomatic-0.32/adapters/TruSeq2-PE.fa')
('trimmomatic_c_thresh', '=', 10)
('trimmomatic_keep_both_reads', '=', 'True')
('trimmomatic_min_adapter_len', '=', 1)
('trimmomatic_mismatches', '=', 1)
('trimmomatic_options', '=', 'LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36')
('trimmomatic_p_thresh', '=', 30)
```

The only difference when comparing this branch with master is:
```
('trimmomatic_keep_both_reads', '=', 1)
```

`master` has:
```
('trimmomatic_keep_both_reads', '=', 'True')
```

As a consequence, there is a difference in the output file `test_readqc.dir/processed.dir/trimmed-SRR078586-X-R1-trimmomatic.log`. On this branch:
```
Input Read Pairs: 78487 Both Surviving: 70170 (89.40%) Forward Only Surviving: 2505 (3.19%) Reverse Only Surviving: 2729 (3.48%) Dropped: 3083 (3.93%)
```

`master` has:
```
Input Read Pairs: 78487 Both Surviving: 70235 (89.49%) Forward Only Surviving: 2440 (3.11%) Reverse Only Surviving: 2738 (3.49%) Dropped: 3074 (3.92%)
```

Not sure whether this is causing the differences downstream.

**Comment by sebastian-luna-valero** [comment]
After merging this branch with the latest `master`, I get:
```
$ python /ifs/devel/sebastian/CGATPipelines/CGATPipelines/pipeline_readqc.py printconfig | grep -i trimmomatic_keep_both_reads
('trimmomatic_keep_both_reads', '=', 'True')
```

and all regression tests are passing locally, so I am now happy to merge. Travis errors are due to expected incompatibilities with Py2-only code on Py3 tests.

Not sure where the value `1` above for `trimmomatic_keep_both_reads` was being read from, but it seems to be causing the different results obtained with `trimmomatic`.

**Comment by Charlie-George** [comment]
Yes - that's exactly it thanks Sebastian - the old default in the readqc ('trimmomatic_keep_both_reads', '=', 1) doesn't do anything '1' should instead be 'True' - I changed this and updated the tests to reflect it. Pulling the master into the test branch should correct it.


Dr Charlotte L. George
CGAT Career Development Fellow | http://www.cgat.org<https://owa.nexus.ox.ac.uk/owa/redir.aspx?C=tDasK99q_keZj7oorbJhL4al53yikdEI0wiICundIwNzuN4H3GD6ZxCoDwZJWAhGr9unzjH9TTY.&URL=http%3a%2f%2fwww.cgat.org>
MRC Centre for Computational Biology| University of Oxford
Weatherall Institute of Molecular Medicine

Tel: +44 1865 222145
________________________________

**Comment by sebastian-luna-valero** [comment]
Many thanks for confirming @Charlie-George !

**Pull request merged**
