### PR TITLE
Ac pipeline pub

### PR DESCRIPTION
**Pull request by Acribbs**
@sebastian-luna-valero would you be able to look over this please. I would like to do some testing of the tests since I have now got a py36 environment and pysam is now upgraded.

### CODE REVIEW

**Comment by Acribbs** [comment]
@sebastian-luna-valero @AndreasHeger This branch contains all of the new pipelines and changes to the old obsolete pipleines. The code is pysam 0.13 compatible. I think the pipelines should be tested in detail before merging because a lot of changes have been made since I last ran full testing. @sebastian-luna-valero kindly said he would test this on the new py36 environment.

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs will work on this next week.

**Comment by sebastian-luna-valero** [comment]
Hi @Acribbs 

Here are some errors that I got after testing this branch (along with `AC-pysam_changes`).

Please let me know your thoughts. Locally we are using `subread=1.4` while version 1.5 is being used in the conda environment for `pipeline_testing`. I think we should update our code to work with subread 1.5. Could you please have a look?

Best regards,
Sebastian

* Running the tests for `scrnaseqqc`
```
    Exception #1
      'builtins.OSError(---------------------------------------
    Child was terminated by signal 134: 
    The stderr was: 
    The '-b' option has been deprecated.
     FeatureCounts will automatically examine the file format.
    
            ==========     _____ _    _ ____  _____  ______          _____  
            =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
              =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
                ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
                  ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
            ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
    	  v1.5.3
    
    //========================== featureCounts setting ===========================\\
    ||                                                                            ||
    ||             Input files : 1 BAM file                                       ||
    ||                           P dedup.dir/ERR_179_7278.dedup.bam               ||
    ||                                                                            ||
    ||             Output file : feature_counts.dir/ERR_179_7278.dedup_vs_ref ... ||
    ||                 Summary : feature_counts.dir/ERR_179_7278.dedup_vs_ref ... ||
    ||              Annotation : ercc.dir/reference.ercc.gtf (GTF)                ||
    ||      Dir for temp files : feature_counts.dir                               ||
    ||                                                                            ||
    ||                 Threads : 4                                                ||
    ||                   Level : meta-feature level                               ||
    ||              Paired-end : no                                               ||
    ||         Strand specific : reversely stranded                               ||
    ||      Multimapping reads : counted                                          ||
    || Multi-overlapping reads : not counted                                      ||
    ||   Min overlapping bases : 1                                                ||
    ||                                                                            ||
    \\===================== http://subread.sourceforge.net/ ======================//
    
    //================================= Running ==================================\\
    ||                                                                            ||
    || Load annotation file ercc.dir/reference.ercc.gtf ...                       ||
    ||    Features : 900002                                                       ||
    ||    Meta-features : 54068                                                   ||
    ||    Chromosomes/contigs : 116                                               ||
    ||                                                                            ||
    || Process BAM file dedup.dir/ERR_179_7278.dedup.bam...                       ||
    ||    Paired-end reads are included.                                          ||
    ||    Assign reads to features...                                             ||
    UnknownTag=
    featureCounts: input-files.c:3273: SAM_pairer_iterate_tags: Assertion `0' failed.
    /ifs/projects/sebastian/pipeline-testing-new-pipelines/test1/test_scrnaseqqc.dir/ctmp9jy58ryz: line 29: 10475 Aborted                 featureCounts -Q 1 -M -T 4 -s 2 -b -a ercc.dir/reference.ercc.gtf -o feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv dedup.dir/ERR_179_7278.dedup.bam > feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv.log
    
    checkpoint;     featureCounts -Q 1 -M     -T 4     -s 2     -b     -a ercc.dir/reference.ercc.gtf     -o feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv     dedup.dir/ERR_179_7278.dedup.bam     > feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv.log;     checkpoint;     gzip feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv
    -----------------------------------------)' raised in ...
       Task = def buildFeatureCounts(...):
       Job  = [[dedup.dir/ERR_179_7278.dedup.bam, ercc.dir/reference.ercc.gtf] -> feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv.gz]
    
    Traceback (most recent call last):
      File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/pipeline_scrnaseqqc.py", line 537, in buildFeatureCounts
        P.run()
      File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/Pipeline/Execution.py", line 548, in run
        ignore_errors=ignore_errors)
      File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/Pipeline/Cluster.py", line 327, in collectSingleJobFromCluster
        "".join(stderr), statement))
    OSError: ---------------------------------------
    Child was terminated by signal 134: 
    The stderr was: 
    The '-b' option has been deprecated.
     FeatureCounts will automatically examine the file format.
    
            ==========     _____ _    _ ____  _____  ______          _____  
            =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
              =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
                ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
                  ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
            ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
    	  v1.5.3
    
    //========================== featureCounts setting ===========================\\
    ||                                                                            ||
    ||             Input files : 1 BAM file                                       ||
    ||                           P dedup.dir/ERR_179_7278.dedup.bam               ||
    ||                                                                            ||
    ||             Output file : feature_counts.dir/ERR_179_7278.dedup_vs_ref ... ||
    ||                 Summary : feature_counts.dir/ERR_179_7278.dedup_vs_ref ... ||
    ||              Annotation : ercc.dir/reference.ercc.gtf (GTF)                ||
    ||      Dir for temp files : feature_counts.dir                               ||
    ||                                                                            ||
    ||                 Threads : 4                                                ||
    ||                   Level : meta-feature level                               ||
    ||              Paired-end : no                                               ||
    ||         Strand specific : reversely stranded                               ||
    ||      Multimapping reads : counted                                          ||
    || Multi-overlapping reads : not counted                                      ||
    ||   Min overlapping bases : 1                                                ||
    ||                                                                            ||
    \\===================== http://subread.sourceforge.net/ ======================//
    
    //================================= Running ==================================\\
    ||                                                                            ||
    || Load annotation file ercc.dir/reference.ercc.gtf ...                       ||
    ||    Features : 900002                                                       ||
    ||    Meta-features : 54068                                                   ||
    ||    Chromosomes/contigs : 116                                               ||
    ||                                                                            ||
    || Process BAM file dedup.dir/ERR_179_7278.dedup.bam...                       ||
    ||    Paired-end reads are included.                                          ||
    ||    Assign reads to features...                                             ||
    UnknownTag=
    featureCounts: input-files.c:3273: SAM_pairer_iterate_tags: Assertion `0' failed.
    /ifs/projects/sebastian/pipeline-testing-new-pipelines/test1/test_scrnaseqqc.dir/ctmp9jy58ryz: line 29: 10475 Aborted                 featureCounts -Q 1 -M -T 4 -s 2 -b -a ercc.dir/reference.ercc.gtf -o feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv dedup.dir/ERR_179_7278.dedup.bam > feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv.log
    
    checkpoint;     featureCounts -Q 1 -M     -T 4     -s 2     -b     -a ercc.dir/reference.ercc.gtf     -o feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv     dedup.dir/ERR_179_7278.dedup.bam     > feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv.log;     checkpoint;     gzip feature_counts.dir/ERR_179_7278.dedup_vs_reference.ercc.tsv
    -----------------------------------------
```

**Comment by sebastian-luna-valero** [comment]
Hi @Acribbs 

Please have a look below at another issue found when testing `bamstats`.

Best regards,
Sebastian

```
                                               Original exception:
                                               
                                                   Exception #1
                                                     'builtins.OSError(---------------------------------------
                                                   Child was terminated by signal 1: 
                                                   The stderr was: 
                                                   Error in library("DT") : there is no package called 'DT'
                                                   Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
                                                   In addition: Warning message:
                                                   In in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE,  :
                                                     You changed the working directory to /ifs/projects/sebastian/pipeline-testing-new-pipelines/test1/test_bamstats.dir (probably via setwd()). It will be restored to /ifs/projects/sebastian/pipeline-testing-new-pipelines/test1/test_bamstats.dir/R_report.dir. See the Note section in ?knitr::knit
                                                   Execution halted
                                                   
                                                   cp /ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/pipeline_docs/pipeline_bamstats/R_report/* R_report.dir ; cd R_report.dir ; R -e "rmarkdown::render_site()"
                                                   -----------------------------------------)' raised in ...
                                                      Task = def renderRreport(...):
                                                      Job
                                                   
                                                   Traceback (most recent call last):
                                                     File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
                                                       register_cleanup, touch_files_only)
                                                     File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 540, in job_wrapper_generic
                                                       return user_defined_work_func(*params)
                                                     File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/pipeline_bamstats.py", line 813, in renderRreport
                                                       P.run()
                                                     File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/Pipeline/Execution.py", line 548, in run
                                                       ignore_errors=ignore_errors)
                                                     File "/ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/Pipeline/Cluster.py", line 327, in collectSingleJobFromCluster
                                                       "".join(stderr), statement))
                                                   OSError: ---------------------------------------
                                                   Child was terminated by signal 1: 
                                                   The stderr was: 
                                                   Error in library("DT") : there is no package called 'DT'
                                                   Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library
                                                   In addition: Warning message:
                                                   In in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE,  :
                                                     You changed the working directory to /ifs/projects/sebastian/pipeline-testing-new-pipelines/test1/test_bamstats.dir (probably via setwd()). It will be restored to /ifs/projects/sebastian/pipeline-testing-new-pipelines/test1/test_bamstats.dir/R_report.dir. See the Note section in ?knitr::knit
                                                   Execution halted
                                                   
                                                   cp /ifs/projects/sebastian/pipeline-testing-new-pipelines/cgat-pipelines/CGATPipelines/pipeline_docs/pipeline_bamstats/R_report/* R_report.dir ; cd R_report.dir ; R -e "rmarkdown::render_site()"
                                                   -----------------------------------------
```

**Comment by Acribbs** [comment]
Hi Sebastian, im a little perplexed by the first issue because I dont think anything obvious in the code has changed to get this error. **Edit**: I have just seen that -b option is deprecated. I will look at alternatives tomorrow. Is it possible that I can test  using the same environment  that you are using to test this? The second issue is likely because the DT package in r isn't installed. This is a library for displaying tables correctly in r, is the DT package installed on the conda environment?.

**Comment by sebastian-luna-valero** [comment]
Thanks, Adam. I confirm installing DT with conda solves the `bamstats` issue. Let's have a look then to the `featureCounts` issue later on.

**Comment by sebastian-luna-valero** [comment]
Indeed, using `subread` version `1.4.6` fixes the issue. 

@CGATOxford/contributors we could not find what `-b` stands for in `featureCounts 1.4.6`, does anyone know?

The `scrnaseqqc` pipeline breaks when we upgrade `featureCounts` to version 1.5.3, since the `-b` has been deprecated.

**Comment by MikeDMorgan** [comment]
I think it should be pretty safe to remove -b, I think it previously was used to define the input as bam.  I haven't had any issues with featureCounts outside the pipelines without this flag.

**Comment by sebastian-luna-valero** [comment]
Many thanks @MikeDMorgan

**Pull request merged**
