### PR TITLE
I have modified the pipeline.ini and specified max and min arguments …

### PR DESCRIPTION
**Pull request by jencyw**
…for sicer peakcaller

### CODE REVIEW

**Comment by Acribbs** [comment]
Please don't merge this branch yet, I have just identified another issue relating to naming of the module files in sicer

**Comment by jencyw** [comment]
@sebastian-luna-valero I have tested the pipeline and @Acribbs agrees that this should be merged once you have looked over it.

**Comment by sebastian-luna-valero** [comment]
Thanks both. Just reverted the unknown values for the annotations database to enforce proper configuration by end user.

**Comment by Acribbs** [comment]
Brilliant, Thanks a lot @sebastian-luna-valero

**Pull request merged**
