### PR TITLE
deseq size factors was producing inf values, have defaulted to normal…

### PR DESCRIPTION
**Pull request by Acribbs**
…isation with simple total-column until issue is identified

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Thanks, Adam.

I would like a second opinion on this one. @CGATOxford/contributors do you agree?

**Comment by AndreasHeger** [comment]
Not quite sure, it seems to me that it is quite desirable to have deseq size factors for the normalization. If there are issues computing them, best solved upstream?

**Comment by Acribbs** [comment]
I have been unable to locate the precise issue and it may take sometime to pinpoint the problem (It was an issue that was raised during the SCRUM and @haniap also looked into this) but I assumed that because the normalisation was only used for summary_plotting it shouldn't be too much of an issue if it was defaulted to total-column. Currently the pipeline breaks unless it uses total-column.

**Comment by AndreasHeger** [comment]
ok. Is it a frequent occurrence? If not, then I would test for inf values and only then use normalization by total.

**Comment by Acribbs** [comment]
It seems to happen to all of my data and I think @haniap has the same issue with her data.

**Comment by AndreasHeger** [comment]
Ok. Make the change and we can revert later. Remind me to debug upstream. It would be good if the deseq size normalization worked.

**Comment by Acribbs** [comment]
@sebastian-luna-valero can we merge?

**Comment by sebastian-luna-valero** [comment]
I was wondering whether @TomSmithCGAT @jscaber @Charlie-George @IanSudbery or @jethrojohnson can comment on this issue as they have previously contributed to this pipeline as well.

It looks to me as if we were solving one problem here and then creating new ones.

@Acribbs have you had a look at the code here:
https://github.com/CGATOxford/cgat/blob/master/CGAT/Counts.py#L167

in which line are you getting `inf` values?

**Comment by Acribbs** [comment]
The issue is that if I use "deseq-size-factors" to normalise the data for producing PCA plots Inf values are created in the columns for certain samples, therefore I assume there must be a division by zero somewhere. Its not consistent throughout all of the samples too. Out of 15 samples, only some show columns of Inf values. Hania also has the same issue.

I haven't had time to fully debug the issue. At the moment the code doesn't work in its present form unless "total-column" is used to normalise. Since we were supposed to close all branches I wanted to merge this so the pipeline is functional again. But if the branch can stay open during the Py3 change then I can debug with @AndreasHeger when we both have time?

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs 

Could you please run the regression tests on this branch as explained here: https://github.com/CGATOxford/CGATPipelines/pull/280#issuecomment-277614681

and confirm whether the tests pass?

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs 

All tests passing now locally. Travis errors are due to a `pysam` update that will be fixed soon so I am going to merge this into the master.

**Pull request merged**
