### PR TITLE
Ajbt cluster pbs pro

### PR DESCRIPTION
**Pull request by antoniojbt**
Hello, additions to Cluster.py so that it also supports working with PBSPro.
Antonio

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Thanks @AntonioJBT 

I will have a look at it after solving the conda installation problem we currently have.

**Comment by antoniojbt** [comment]
Great, thanks.

**Comment by antoniojbt** [comment]
Hi Sebastian,
Travis gets stuck at:

> WARNING:
> 
>  could not import _license.show_info
> # try:
> # $ conda install -n root _license
> Fetching package metadata ...............
> Solving package specifications: .
> 
> No output has been received in the last 10m0s,
 
Full log attached.
[raw_log_travis_build_1101.2_139217697.txt](https://github.com/CGATOxford/CGATPipelines/files/716130/raw_log_travis_build_1101.2_139217697.txt)

Anything I can do?
Antonio

**Comment by sebastian-luna-valero** [comment]
Hi Antonio,

Your branch is now merged with the latest master branch and looking green. Should I merge now or is there anything else to add to this PR?

Best regards,
Sebastian

**Comment by antoniojbt** [comment]
Thanks! We can go ahead, nothing to add for now.
Best,
Antonio

**Pull request merged**
