### PR TITLE
SLURM

### PR DESCRIPTION
**Pull request by snsansom**
Andreas/Sebastian please take a look!

This: 

(1) adds support for the SLURM queue manager assuming that it is configured with consumable resources as commented in the code (a standard configuration profile).

We are using SLURM on our cluster so this should get extensive testing.

(2) implements site-wide configuration in /etc/cgat/. Here /etc/cgat/pipeline.ini is used for pipeline configuration, analogously /etc/cgat/scripts.ini could be used for the CGAT scripts collection.

This is needed to allow straightforward (i.e. administrator rather than user configured)  deployment of the code on foreign clusters.

### CODE REVIEW

**Comment by IanSudbery** [comment]
Hi Steve,

Just a note to say that the '-V' option passed to SGE signifies that the current environment (i.e. the state of environment variables in the current login session) should be passed to the session on the worker node. This ensures that things like the current working dir and the contents of PATH are the same on the head node and the worker node. 

I don't know if this would be necessary for SLURM.

**Comment by snsansom** [comment]
Aha good to know, thanks - I'll amend the comment when I next commit. I understand that SLURM passes all environment variables by default - I am able to run pipelines with this code using SLURM on a test server.

**Comment by AndreasHeger** [comment]
Sorry, can't go through this in detail, but looks good on first view. Many thanks! 

I don't think that hard-coded params should go to /etc/cgat, because cgat should in principle be installabe and runnable without having root access.

**Comment by snsansom** [comment]
Thanks Andreas. 

I would then suggest that hard coded params go to CGATPipelines/Pipelines/pipeline.ini and that parameters are:

(1) First set from .../CGATPipelines/Pipelines/pipeline.ini
(2) Updated from /etc/cgat/pipeline.ini (_if exists_)
(3) Updated from ~/.cgat/pipeline.ini (_if exists_)
(4) etc

This would make it trivial for admins/users to clone the config file and amend as required site-wide or per user. How about that?

**Comment by sebastian-luna-valero** [comment]
Many thanks All.

According to the documentation, the existing code already accounted for user-defined configuration files:

```
The order of initialization is as follows:
    1. hard-coded defaults
    2. pipeline specific default file in the CGAT code installation
    3. :file:`.cgat` in the users home directory
    4. files supplied by the user in the order given
    If the same configuration value appears in multiple
    files, later configuration files will overwrite the
    settings form earlier files.
```

Have you tried that, Steve? 

If that did not work for you, but these amendments do, then please update the documentation of the code accordingly.

Other than that, your approach to work either with SGE or SLURM is quite nice.

Many thanks,
Sebastian.

**Comment by AndreasHeger** [comment]
Thanks. I think keeping a /etc/cgat.ini is fine. In addition to a user ini it will allow an admin to set site-wide preferences so users need not be aware of cluster configuration.

However, hardcoded defaults should stay within the code.

**Pull request merged**
