### PR TITLE
runFeatureCounts in PipelineRnaseq.py trys to create a temporary dire…

### PR DESCRIPTION
**Pull request by nickilott**
…ctory twice - this fix removes mkdir (tmpdir) from commandline statement

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Thanks @nickilott 

When I run `pipeline_testing` on your branch I get a problem in the `runFeatureCounts` task of  [pipeline_rnaseqdiffexpression](https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_rnaseqdiffexpression.py#L691)

The error is:
```
Original exceptions:

    Exception #1
      'builtins.OSError(---------------------------------------
    Child was terminated by signal 1: 
    The stderr was: 
    /ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/testing/test_rnaseqdiffexpression.dir/ctmpye6jf6g2: line 29: /scratch/ctmppdc07kfb/geneset.gtf: No such file or directory
    
    zcat refcoding.gtf.gz > /scratch/ctmppdc07kfb/geneset.gtf;                        checkpoint;                                                featureCounts -Q 10                                      -T 4                               
       -s 0                                      -a /scratch/ctmppdc07kfb/geneset.gtf                                                                            -o featurecounts.dir/Brain-F1-R1/transcripts.tsv.raw -g transcript_id       
                               Brain-F1-R1.bam                         >& featurecounts.dir/Brain-F1-R1/transcripts.tsv.gz.log;                         rm -rf /scratch/ctmppdc07kfb; checkpoint;                         gzip -f featurecoun
ts.dir/Brain-F1-R1/transcripts.tsv.raw
    -----------------------------------------)' raised in ...
       Task = def runFeatureCounts(...):
       Job  = [[Brain-F1-R1.bam, refcoding.gtf.gz] -> [featurecounts.dir/Brain-F1-R1/transcripts.tsv.gz, featurecounts.dir/Brain-F1-R1/genes.tsv.gz]]
    
    Traceback (most recent call last):
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/conda-install/envs/cgat-p/lib/python3.6/site-packages/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/cgat-pipelines/CGATPipelines/pipeline_rnaseqdiffexpression.py", line 691, in runFeatureCounts
        Quantifier.run_all()
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/cgat-pipelines/CGATPipelines/PipelineRnaseq.py", line 241, in run_all
        self.run_transcript()
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/cgat-pipelines/CGATPipelines/PipelineRnaseq.py", line 322, in run_transcript
        self.run_featurecounts(level="transcript_id")
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/cgat-pipelines/CGATPipelines/PipelineRnaseq.py", line 314, in run_featurecounts
        P.run()
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/cgat-pipelines/CGATPipelines/Pipeline/Execution.py", line 552, in run
        ignore_errors=ignore_errors)
      File "/ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/cgat-pipelines/CGATPipelines/Pipeline/Cluster.py", line 326, in collectSingleJobFromCluster
        "".join(stderr), statement))
    OSError: ---------------------------------------
    Child was terminated by signal 1: 
    The stderr was: 
    /ifs/projects/sebastian/NEI-rnaseqdiffexpression-bugfix/testing/test_rnaseqdiffexpression.dir/ctmpye6jf6g2: line 29: /scratch/ctmppdc07kfb/geneset.gtf: No such file or directory
    
    zcat refcoding.gtf.gz > /scratch/ctmppdc07kfb/geneset.gtf;                        checkpoint;                                                featureCounts -Q 10                                      -T 4                               
       -s 0                                      -a /scratch/ctmppdc07kfb/geneset.gtf                                                                            -o featurecounts.dir/Brain-F1-R1/transcripts.tsv.raw -g transcript_id       
                               Brain-F1-R1.bam                         >& featurecounts.dir/Brain-F1-R1/transcripts.tsv.gz.log;                         rm -rf /scratch/ctmppdc07kfb; checkpoint;                         gzip -f featurecoun
ts.dir/Brain-F1-R1/transcripts.tsv.raw
    -----------------------------------------
```

Please let me know your thoughts.

Best regards,
Sebastian

**Comment by nickilott** [comment]
Hmmm, I think this relates to #174 - it might be best to re-write this task in the suggested form:

mytmp=`mktemp -d %(local_tmpdir)s` 

etc

What do you think?

**Comment by sebastian-luna-valero** [comment]
Thanks!

Could you please re-write the task, test it on your end and push the changes so I can pull and test in our environment?

Best regards,
Sebastian

**Comment by nickilott** [comment]
I have (un)expectedly ended up down a bit of a rabbit hole with this one with multiple tempfiles and output weirdnesses. Will have a look again tomorrow and see if I can get it working!

**Comment by sebastian-luna-valero** [comment]
Thanks!

**Comment by nickilott** [comment]
Hi @sebastian-luna-valero 
I have re-written the task and it works at my end. The code has been altered quite a lot as after a bit of thought I thought it best to have separate statements for paired-end and single-end data - it got rid of a lot of complexity of string substitutions for multiple temp files (that were difficult to access) and I think the code is nicer to look at this way albeit with some redundancy.

**Comment by sebastian-luna-valero** [comment]
Hi @nickilott 

Great, it is also working at my end so I will merge.

On the other hand, regarding the creation of temporary files, I think this has been solved globally in the new repo. Please see:
* `cgat-core`
https://github.com/cgat-developers/cgat-core/blob/master/CGATCore/Pipeline/Files.py#L16
* `cgat-flow`
https://github.com/cgat-developers/cgat-flow/blob/master/CGATPipelines/PipelineRnaseq.py#L1051

I will revisit this PR to make sure your changes work with the new `Pipeline.py` API.

Best regards,
Sebastian

**Comment by nickilott** [comment]
Thanks @sebastian-luna-valero, 
What is the main difference in how Pipeline.py now handles temporary files?

**Comment by sebastian-luna-valero** [comment]
Here is the new code:
https://github.com/cgat-developers/cgat-core/blob/master/CGATCore/Pipeline/Files.py#L92

**Comment by nickilott** [comment]
P.S sorry its taken so long to get around to this

**Pull request merged**
